<!-- include file: menu.inc; start -->
<ul class="linklist">
<li><a href="index.html" accesskey="h" title="Philip Wellnitz Homepage" id="hp-index">Philip Wellnitz:</a>
<ul>
<li><a href="index.html#publications" accesskey="p" title="Publications of Philip Wellnitz" id="hp-publications">Selected <span class="ak">P</span>ublications</a></li>
<li><a href="index.html#teaching" accesskey="t" title="Teaching of Philip Wellnitz" id="hp-teaching"><span class="ak">T</span>eaching</a></li>
</ul>
</li>
<!-- CHANGE HERE: Put your own menu items here. They can also point to different html pages. -->
<!-- Make sure to highlight the page you are on using the style section on top of that page -->
</ul>
<!-- include file: menu.inc; end -->

